### ISSUE TITLE
UI cleanup 

### ISSUE THREAD

**Issue by jigneng1** [bodangren/reading-advantage#10]
- [x] Show RA level and CEFR level in top of article
- [x] Make breadcrumb look like button and show progress bar
- [x] use dropdown menu 
- [x] show input result

**Comment by bodangren** [comment]
Breadcrumbs already look like buttons. This is confusing for users. Let's change the look or change the functionality.

**Comment by jigneng1** [comment]
I will change Breadcrumbs, because change the function of the button is so complicated

**Comment by bodangren** [comment]
Good choice.

**Comment by jigneng1** [comment]
<img width="1552" alt="image" src="https://github.com/bodangren/reading-advantage/assets/83826754/741ecf78-a013-4609-8012-71d3ea83cb28">

**Comment by bodangren** [comment]
Perfect
